#!/usr/bin/env bash
# displays Best School 10 times.
counter=0
while [ $counter -lt 10 ]
    do
    if [ $counter = 8 ]
        then
            echo "Hi"
        else
            echo "Best School"
        fi
    let counter++
done