#!/usr/bin/env bash
# displays Best School 10 times.
counter=0
while [ $counter -lt 11 ]
do
    if [ $counter = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done