#!/usr/bin/env bash
# displays numbers from 1 to 20.
counter=1
while [ $counter -lt 20 ]
do
    if [ $counter = 4 ]; then
        echo "bad luck from China"
    elif [ $counter = 9 ]; then
        echo "bad luck from Japan"
    elif [ $counter = 17 ]; then
        echo "bad luck from Italy"
    else
        echo $counter
    fi
    ((counter++))
done